let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Fourth Wing",
    price: 230,
    desc: "Rebecca Yarros",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTMGygN6vmJYLi9nkL769kQfNDg3kt-zfrb1AQRkAnvtiUysGdh",
  },
  {
    id: "ioytrhndcv",
    name: "Home Coming",
    price: 200,
    desc: "Kate Morton",
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTdImt2D_V-w99CEgp8XSAHdY7b9Nn4X3psOKamAgFHYDuhygfZ" ,
  },
  {
    id: "wuefbncxbsn",
    name: "Verity",
    price: 200,
    desc: "Colleen Hoover",
    img: "https://storage.googleapis.com/du-prd/books/images/9781791392796.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "The Covenant of Water",
    price: 180,
    desc: "Abraham Verghese",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRJZVwqx1GnTJ10pLHwEjssuO7_T3wudCMMmSAjhUxXuh42XCD4",
  },
  {
    id: "thiecbawdjksadjk",
    name: "To Kill A Mockingbird",
    price: 360,
    desc: "Harper Lee",
    img: "https://m.media-amazon.com/images/I/41j-s9fHJcL.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Adventures of Huckleberry Finn",
    price: 190,
    desc: "Mark Twain",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQLFFtRQybT035PZLJUlFryBFiWZAjxGvjblf0tDwJbpBIY5Gau" ,
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Harry Potter and the Half-Blood Prince",
    price: 340,
    desc: "JK Rowling",
    img: "https://media1.popsugar-assets.com/files/thumbor/p5eA5UkapI5PQFIoK4MavuVcnBU=/fit-in/750x1200/filters:format_auto():upscale()/2018/06/27/237/n/1922283/a5b50629e4167f96_harry-potter-and-the-half-blood-prince-6.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Mahashweta",
    price: 95,
    desc: "Sudha Murthy",
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/regionalbooks/d/x/i/mahasweta-sudha-murthy-book-original-imagnfrrzryrafsx.jpeg?q=90",
  },
  {
    id: "cbvxbcvsceldk",
    name: "SITA-Warrior of Mithila",
    price: 220,
    desc: "Amish Tripathi",
    img: "https://onlinereadfreenovel.com/i2/amish-tripathi/sita_warrior_of_mithila.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Cosmos",
    price: 320,
    desc: "Carl Sagan",
    img: "https://www.bookganga.com/eBooks/Content/images/books/694e8833fad94f95816b5dd81e6b27c1.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "The Cruel Prince",
    price: 300,
    desc: "Holly Black",
    img: "https://images.meesho.com/images/products/236291628/ptc34_512.webp",
  },
  {
    id: "rtytytuyuytyytbvncvytrew",
    name: "Malgudi Days",
    price: 140,
    desc: "R K Narayan",
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1644689955i/14082.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "The Fault in our Stars",
    price: 210,
    desc: "John Green",
    img: "https://www.crossword.in/cdn/shop/products/9780141345659.jpg?v=1680189805",
  },
  {
    id: "rtytytuyuytyytbvncvb",
    name: "House of Sky and Breath",
    price: 340,
    desc: "Sarah J Maas",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLX_Z_qzJBOiKdvhElm1PoEdRmP8QrulhYx-dQxhvlto-bVz1u",
  },
  {
    id: "rtytytuyuytyytbvncvwe",
    name: "Norwegian Wood",
    price: 365,
    desc: "Murakami",
    img: "https://www.crossword.in/cdn/shop/products/9780099448822.jpg?v=1680186521",
  },
  {
    id: "rtytytuyuytyytbvncvti",
    name: "The Monk who sold his Ferrari",
    price: 250,
    desc: "Robin Sharma",
    img: "https://www.crossword.in/cdn/shop/products/9788179921623.jpg?v=1680196770",
  },
];
